apiVersion: v1
kind: ResourceQuota
metadata:
  name: resourcequota-backend-ktb
  namespace: prod
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "2Gi"
    limits.cpu: "3"
    limits.memory: "3Gi"
    pods: "10"