apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange-backend-ktb
  namespace: prod
spec:
  limits:
    - type: Container
      min:
        cpu: "100m"
        memory: "128Mi"
      max:
        cpu: "1200m"
        memory: "1Gi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "250m"
        memory: "256Mi"