spring:
  application:
    name: KTB

  profiles:
    active: local


  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  session:
    store-type: redis
    timeout: 30m
    redis:
      namespace: ktb:session


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false       # true, false
        use_sql_comments: true
    open-in-view: true          # false


  servlet:
    multipart:
      enabled: true             # 멀티파트 처리 (기본 true)
      max-file-size: 4MB        # 파일 1개 최대 크기 (기본 2MB)
      max-request-size: 10MB    # 요청 전체 합 (기본 10MB)
      resolve-lazily: true      # multipart 파싱 지연 처리 (선택)

file:
  upload-path: uploads