spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ktb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create            # none, validate, update, create, create-drop
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  config:
    import: application-monitoring.yml