# --- 복제본 ---
replicaCount: 2

# --- 이미지 ---
image:
  repository: 925663248026.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-ktb
  tag: latest
  # pullPolicy 생략 → latest면 자동 Always

# --- 컨테이너 포트 ---
containerPort: 8080

# --- 리소스 ---
resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "768Mi"

# --- Probe 타이밍 ---
probe:
  startup:
    periodSeconds: 5
    failureThreshold: 12
    timeoutSeconds: 3
  readiness:
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 3
  liveness:
    periodSeconds: 15
    failureThreshold: 3
    timeoutSeconds: 3

# --- ConfigMap 데이터 ---
config:
  DB_HOST: "az1-rds-ktb.cn624i4wilx0.ap-northeast-2.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "ktb"
  REDIS_HOST: "elasticcache-redis-ktb-001.twp2ye.ng.0001.apn2.cache.amazonaws.com"
  REDIS_PORT: "6379"
  DDL_AUTO: "update"
  S3_BUCKET: "s3-bucket-ktb"
  SPRING_PROFILES_ACTIVE: "prod"

# --- secret ---
secretName: "secret-backend-ktb"

# --- ResourceQuota ---
quota:
  requests:
    cpu: "1"
    memory: "2Gi"
  limits:
    cpu: "3"
    memory: "3Gi"
  pods: "10"

# --- LimitRange ---
limitRange:
  max:
    cpu: "1200m"
    memory: "1Gi"

# --- Ingress ---
ingress:
  enabled: false

# --- Rolling Update strategy ---
strategy:
  maxUnavailable: 0
  maxSurge: 1

# --- affinity ---
affinity:
  weight: 100

#image:
#  repository: nginx
#  pullPolicy: IfNotPresent
#  tag: ""
#
#imagePullSecrets: []
#
#nameOverride: ""
#fullnameOverride: ""
#
#serviceAccount:
#  create: true
#  automount: true
#  annotations: {}
#  name: ""
#
#podAnnotations: {}
#
#podLabels: {}
#
#podSecurityContext: {}
#
#securityContext: {}
#
#service:
#  type: ClusterIP
#  port: 80
#
#ingress:
#  enabled: false
#  className: ""
#  annotations: {}
#  hosts:
#    - host: chart-example.local
#      paths:
#        - path: /
#          pathType: ImplementationSpecific
#  tls: []
#
#httpRoute:
#  enabled: false
#  annotations: {}
#
#  parentRefs:
#    - name: gateway
#      sectionName: http
#
#  hostnames:
#    - chart-example.local
#
#  rules:
#    - matches:
#        - path:
#            type: PathPrefix
#            value: /headers
#
#
#resources: {}
#
#
#livenessProbe:
#  httpGet:
#    path: /
#    port: http
#
#
#readinessProbe:
#  httpGet:
#    path: /
#    port: http
#
#
#autoscaling:
#  enabled: false
#  minReplicas: 1
#  maxReplicas: 100
#  targetCPUUtilizationPercentage: 80
#
#
#volumes: []
#
#volumeMounts: []
#
#nodeSelector: {}
#
#tolerations: []
#
#affinity: {}