apiVersion: v1
kind: Service
metadata:
  name: service-backend-spring-api-server-clusterip-ktb
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ktb
    tier: backend
    env: prod
  ports:
    - port: {{ .Values.containerPort }}
