apiVersion: v2
name: umbrella-helm-ktb
description: umbrella helm ktb
type: application
version: 0.1.0

dependencies:
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend-helm"
  - name: cluster
    version: 0.1.0
    repository: "file://charts/cluster-helm"