cluster:
  # --- ResourceQuota ---
  quota:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "3"
      memory: "3Gi"
    pods: "10"

  # --- LimitRange ---
  limitRange:
    min:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "1200m"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    default:
      cpu: "250m"
      memory: "256Mi"