apiVersion: v1
kind: Service
metadata:
  name: service-backend-spring-api-server-clusterip-ktb
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  selector:
    app: ktb
    tier: backend
    env: prod
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
